[tool.poetry]
name = "GamestonkTerminal"
version = "0.1.0"
description = ""
authors = ["Didier Rodrigues Lopes"]

[tool.poetry.dependencies]
python = "^3.6.8"
fbprophet = "^0.6"
pandas = "^1.1.5"
iso8601 = "^0.1.14"
FundamentalAnalysis = "^0.2.6"
requests = "^2.25.1"
alpha-vantage = "^2.3.1"
finviz = "^1.3.4"
bs4 = "^0.0.1"
rapidfuzz = "^1.1.1"
yfinance = "^0.1.55"
pandas-ta = "^0.2.23b0"
prettytable = "^2.0.0"
psaw = "^0.0.12"
praw = "^7.1.4"
Quandl = "^3.6.0"
flair = "^0.7"
pytrends = "^4.7.3"
TimeSeriesCrossValidation = { git = "https://github.com/DidierRLopes/TimeSeriesCrossValidation.git",  branch = "master" }
pmdarima = "^1.8.0"
tensorflow = "^2.4.1"
matplotlib = "^3.3.3"
plotly = "^4.14.3"
colorama = "^0.4.4"
papermill = "^2.3.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
